// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5risZfVPdYOZA3J6fpXFjTYVsm5L6Rvs',
    appId: '1:67388830832:web:c386e8184acc6a5f6730b5',
    messagingSenderId: '67388830832',
    projectId: 'tmkfmb-95dd7',
    authDomain: 'tmkfmb-95dd7.firebaseapp.com',
    storageBucket: 'tmkfmb-95dd7.firebasestorage.app',
    measurementId: 'G-S6Z7QT26BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmFU8LNu8HjZColbyKOL3mXADarOVi6EI',
    appId: '1:67388830832:android:11f71d084e4df2b16730b5',
    messagingSenderId: '67388830832',
    projectId: 'tmkfmb-95dd7',
    storageBucket: 'tmkfmb-95dd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMyv7fslrkfGbXGLN_1YeJiiZ3EGO_Txs',
    appId: '1:67388830832:ios:15033497e1bd41f46730b5',
    messagingSenderId: '67388830832',
    projectId: 'tmkfmb-95dd7',
    storageBucket: 'tmkfmb-95dd7.firebasestorage.app',
    iosBundleId: 'com.app.fmbApp',
  );

}